# Generated by Django 6.0.1 on 2026-02-05 06:47

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('division', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('upazila', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('total_beds', models.PositiveIntegerField(default=0)),
                ('vacant_beds', models.PositiveIntegerField(default=0)),
                ('icu_beds', models.PositiveIntegerField(default=0)),
                ('available_icu_beds', models.PositiveIntegerField(default=0)),
                ('accepting_referrals', models.BooleanField(default=True)),
                ('has_emergency', models.BooleanField(default=False)),
                ('emergency_level', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3)])),
                ('dept_medicine', models.BooleanField(default=False)),
                ('dept_cardiology', models.BooleanField(default=False)),
                ('dept_neurology', models.BooleanField(default=False)),
                ('dept_gastroenterology', models.BooleanField(default=False)),
                ('dept_pulmonology', models.BooleanField(default=False)),
                ('dept_nephrology', models.BooleanField(default=False)),
                ('dept_orthopedics', models.BooleanField(default=False)),
                ('dept_surgery', models.BooleanField(default=False)),
                ('dept_ent', models.BooleanField(default=False)),
                ('dept_obgyn', models.BooleanField(default=False)),
                ('dept_pediatrics', models.BooleanField(default=False)),
                ('dept_dermatology', models.BooleanField(default=False)),
                ('dept_ophthalmology', models.BooleanField(default=False)),
                ('dept_psychiatry', models.BooleanField(default=False)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('gp', 'General Practitioner'), ('hospital', 'Hospital'), ('guest', 'Guest')], default='guest', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('address', models.TextField(blank=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='recommender_user_set', related_query_name='recommender_user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='recommender_user_set', related_query_name='recommender_user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_age', models.PositiveIntegerField()),
                ('patient_problem', models.TextField()),
                ('department', models.CharField(max_length=50)),
                ('emergency_level', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3)])),
                ('patient_upazila', models.CharField(max_length=100)),
                ('patient_district', models.CharField(max_length=100)),
                ('ai_recommended_hospital', models.CharField(blank=True, max_length=200)),
                ('ai_score', models.FloatField(blank=True, null=True)),
                ('ai_reason', models.TextField(blank=True)),
                ('override_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_received', to='recommender.hospital')),
                ('gp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to='recommender.user')),
            ],
        ),
        migrations.AddField(
            model_name='hospital',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_hospitals', to='recommender.user'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_profile', to='recommender.user'),
        ),
        migrations.CreateModel(
            name='GPProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('specialization', models.CharField(blank=True, max_length=100)),
                ('assigned_upazila', models.CharField(blank=True, max_length=100)),
                ('assigned_district', models.CharField(blank=True, max_length=100)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_gps', to='recommender.user')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gp_profile', to='recommender.user')),
            ],
        ),
    ]
